services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app:cached # 
      - /app/node_modules #
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: spring_backend
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/service_picker
      - SPRING_DATASOURCE_USERNAME=service_picker_user
      - SPRING_DATASOURCE_PASSWORD=service_picker_dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: service_picker
      POSTGRES_USER: service_picker_user
      POSTGRES_PASSWORD: service_picker_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
