--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12 (Debian 15.12-1.pgdg120+1)
-- Dumped by pg_dump version 15.12 (Debian 15.12-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: resumes_access_offer; Type: TABLE; Schema: public; Owner: service_picker_user
--

CREATE TABLE public.resumes_access_offer (
    id bigint NOT NULL,
    access_duration integer,
    area_id integer,
    number_of_contacts integer,
    price double precision,
    profession_id integer
);


ALTER TABLE public.resumes_access_offer OWNER TO service_picker_user;

--
-- Name: resumes_access_offer_id_seq; Type: SEQUENCE; Schema: public; Owner: service_picker_user
--

ALTER TABLE public.resumes_access_offer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resumes_access_offer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vacancy_offer; Type: TABLE; Schema: public; Owner: service_picker_user
--

CREATE TABLE public.vacancy_offer (
    id bigint NOT NULL,
    area_id integer,
    package_volume integer,
    price_per_one double precision,
    price_per_package double precision,
    profession_id integer,
    publication_period integer,
    vacancy_type character varying(255)
);


ALTER TABLE public.vacancy_offer OWNER TO service_picker_user;

--
-- Name: vacancy_offer_id_seq; Type: SEQUENCE; Schema: public; Owner: service_picker_user
--

ALTER TABLE public.vacancy_offer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vacancy_offer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: resumes_access_offer; Type: TABLE DATA; Schema: public; Owner: service_picker_user
--

COPY public.resumes_access_offer (id, access_duration, area_id, number_of_contacts, price, profession_id) FROM stdin;
1	30	1	100	4500	5
2	30	1	100	4500	5
\.


--
-- Data for Name: vacancy_offer; Type: TABLE DATA; Schema: public; Owner: service_picker_user
--

COPY public.vacancy_offer (id, area_id, package_volume, price_per_one, price_per_package, profession_id, publication_period, vacancy_type) FROM stdin;
1	4228	50	100	5000	50	30	Standard
\.


--
-- Name: resumes_access_offer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: service_picker_user
--

SELECT pg_catalog.setval('public.resumes_access_offer_id_seq', 2, true);


--
-- Name: vacancy_offer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: service_picker_user
--

SELECT pg_catalog.setval('public.vacancy_offer_id_seq', 1, true);


--
-- Name: resumes_access_offer resumes_access_offer_pkey; Type: CONSTRAINT; Schema: public; Owner: service_picker_user
--

ALTER TABLE ONLY public.resumes_access_offer
    ADD CONSTRAINT resumes_access_offer_pkey PRIMARY KEY (id);


--
-- Name: vacancy_offer vacancy_offer_pkey; Type: CONSTRAINT; Schema: public; Owner: service_picker_user
--

ALTER TABLE ONLY public.vacancy_offer
    ADD CONSTRAINT vacancy_offer_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

